import type { Metadata } from "next";
import { Poppins, Dancing_Script } from "next/font/google";
import "./globals.css";

const font = Poppins({ 
  subsets: ["latin"],
  weight: "400"
});

const dancingScript = Dancing_Script({ // Initialize Dancing Script
  subsets: ["latin"],
  weight: ["400", "700"], // Add multiple weights if needed
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Export dancingScript to use in other components
export { dancingScript };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
